name: Build and Deploy Docusaurus Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy-pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Use Node.js 18.x
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      # Clear NPM cache to avoid corrupted or outdated dependencies
      - name: Clear NPM cache
        run: npm cache clean --force

      # Update the Browserslist database to avoid build issues
      - name: Update Browserslist DB
        run: npx update-browserslist-db@latest

      # Install dependencies with npm ci to ensure consistent versions (using package-lock.json)
      - name: Install dependencies
        run: npm ci --no-audit

      # Build the project with verbose logging to help with any debugging
      - name: Build the Docusaurus site
        run: npm run build --loglevel verbose

      # Add the .nojekyll file to prevent GitHub Pages from processing the site with Jekyll
      - name: Disable Jekyll for GitHub Pages
        run: echo "" > build/.nojekyll

      # Upload the built site as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Check out the repository (for context in deployment)
      - name: Checkout
        uses: actions/checkout@v4

      # Setup for deploying to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
