name: Deploy Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy-pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js 18.x environment
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      # Clear NPM cache to avoid using corrupted caches
      - name: Clear NPM cache
        run: npm cache clean --force

      # Update browserslist database to avoid outdated warnings
      - name: Update Browserslist DB
        run: npx update-browserslist-db@latest

      # Install dependencies using package-lock.json and skip audit temporarily
      - name: Install dependencies
        run: npm ci --no-audit

      # Run the build process with verbose logging to capture detailed errors
      - name: Build project
        run: npm run build --loglevel verbose

      # Disable Jekyll by adding a `.nojekyll` file to the output directory
      - name: Disable Jekyll for GitHub Pages
        run: echo "" > build/.nojekyll

      # Upload the build artifact to be deployed
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup for deploying to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Deploy the build to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
